# Generated by Django 5.2.4 on 2025-10-07 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='spas.spaowner')),
            ],
            options={
                'db_table': 'spa_owners',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Spa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spa_code', models.CharField(max_length=50, unique=True)),
                ('spa_name', models.CharField(max_length=200)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('reopen_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Temporarily Closed', 'Temporarily Closed')], default='Open', max_length=30)),
                ('line_track', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('emails', models.TextField(blank=True, help_text='Comma-separated list of emails', null=True)),
                ('phones', models.TextField(blank=True, help_text='Comma-separated list of phone numbers', null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('agreement_status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Not Avail', 'Not Avail')], default='Not Avail', max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spas', to='location.area')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spas_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spas', to='spas.spaowner')),
                ('sub_owners', models.ManyToManyField(blank=True, related_name='managed_spas', to='spas.spaowner')),
            ],
            options={
                'db_table': 'spas',
                'ordering': ['spa_name'],
                'indexes': [models.Index(fields=['spa_code'], name='idx_spa_code'), models.Index(fields=['status'], name='idx_spa_status'), models.Index(fields=['spa_name'], name='idx_spa_name')],
            },
        ),
    ]
