# Generated by Django 5.2.4 on 2025-10-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourthOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fourth_owners',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='ThirdOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'third_owners',
                'ordering': ['fullname'],
            },
        ),
        migrations.AddField(
            model_name='spa',
            name='fourth_owner',
            field=models.ForeignKey(blank=True, help_text='Fourth Owner (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spas', to='spas.fourthowner'),
        ),
        migrations.AddField(
            model_name='spa',
            name='third_owner',
            field=models.ForeignKey(blank=True, help_text='Third Owner (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spas', to='spas.thirdowner'),
        ),
    ]
