# Generated by Django 5.2.7 on 2025-10-09 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spa',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spas_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spa',
            name='primary_owner',
            field=models.ForeignKey(help_text='Primary Owner (required for spa creation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spas', to='spas.primaryowner'),
        ),
        migrations.AddField(
            model_name='spa',
            name='secondary_owner',
            field=models.ForeignKey(blank=True, help_text='Secondary Owner (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spas', to='spas.secondaryowner'),
        ),
        migrations.AddIndex(
            model_name='spa',
            index=models.Index(fields=['spa_code'], name='idx_spa_code'),
        ),
        migrations.AddIndex(
            model_name='spa',
            index=models.Index(fields=['status'], name='idx_spa_status'),
        ),
        migrations.AddIndex(
            model_name='spa',
            index=models.Index(fields=['spa_name'], name='idx_spa_name'),
        ),
    ]
