# Generated by Django 5.2.4 on 2025-10-15 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0002_fourthowner_thirdowner_spa_fourth_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='spas.spa')),
            ],
            options={
                'db_table': 'spa_managers',
                'ordering': ['fullname'],
            },
        ),
    ]
