# Generated by Django 5.2.7 on 2025-11-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0003_spamanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='spas.spa')),
            ],
            options={
                'db_table': 'spa_social_media_links',
                'ordering': ['platform'],
            },
        ),
    ]
