# Generated by Django 5.2.7 on 2025-12-02 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0004_socialmedialink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Business site', 'business site'), ('Advert site', 'advert site'), ('Booking site', 'booking site')], max_length=100)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_websites_created', to=settings.AUTH_USER_MODEL)),
                ('spa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='spas.spa')),
            ],
            options={
                'db_table': 'spa_websites',
                'ordering': ['url'],
            },
        ),
    ]
