# Generated by Django 5.2.7 on 2025-12-16 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0005_spawebsite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spa',
            name='google_drive_link',
            field=models.URLField(blank=True, help_text='Google Drive link for spa photos and videos', null=True),
        ),
        migrations.CreateModel(
            name='SpaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_media_created', to=settings.AUTH_USER_MODEL)),
                ('spa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='spas.spa')),
            ],
            options={
                'db_table': 'spa_media',
                'ordering': ['url'],
            },
        ),
    ]
