# Generated by Django 5.2.7 on 2025-10-10 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of account holder', max_length=150)),
                ('designation', models.CharField(blank=True, help_text='Designation/Title', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Holder',
                'verbose_name_plural': 'Account Holders',
                'db_table': 'account_holders',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Unique serial number', max_length=100, unique=True)),
                ('machine_code', models.CharField(blank=True, help_text='Unique internal code or ID', max_length=100, null=True)),
                ('machine_name', models.CharField(blank=True, help_text='Display name or identifier', max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, help_text='Model/Type of machine', max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, help_text='Software version', max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, help_text='Account name for transactions', max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name', max_length=150, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=100, null=True)),
                ('mid', models.CharField(blank=True, help_text='Merchant ID', max_length=100, null=True)),
                ('tid', models.CharField(blank=True, help_text='Terminal ID', max_length=100, null=True)),
                ('status', models.CharField(choices=[('in_use', 'In Use'), ('not_in_use', 'Not In Use'), ('broken', 'Broken')], default='in_use', max_length=20)),
                ('remark', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acc_holder', models.ForeignKey(blank=True, help_text='Account holder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='machine.accountholder')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_created', to=settings.AUTH_USER_MODEL)),
                ('spa', models.ForeignKey(blank=True, help_text='Spa where machine is installed (location inherited from spa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='spas.spa')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'db_table': 'machines',
                'ordering': ['spa__spa_name', 'serial_number'],
                'indexes': [models.Index(fields=['serial_number'], name='idx_machine_serial'), models.Index(fields=['machine_code'], name='idx_machine_code'), models.Index(fields=['status'], name='idx_machine_status'), models.Index(fields=['spa'], name='idx_machine_spa')],
            },
        ),
    ]
