# Generated by Django 5.2.4 on 2025-10-07 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('spas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_note', models.CharField(blank=True, help_text='e.g., Front desk, Room 1', max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
                ('activated_at', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_created', to=settings.AUTH_USER_MODEL)),
                ('installed_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='location.area')),
                ('spa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='spas.spa')),
            ],
            options={
                'db_table': 'machines',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('from_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_moves_from', to='location.area')),
                ('from_spa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_moves_from', to='spas.spa')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='machine.machine')),
                ('to_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_moves_to', to='location.area')),
                ('to_spa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_moves_to', to='spas.spa')),
            ],
            options={
                'db_table': 'machine_assignments',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['serial_number'], name='idx_machine_sn'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['spa', 'status'], name='idx_machine_spa_status'),
        ),
    ]
