# Generated by Django 5.2.7 on 2025-10-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
