# Generated by Django 5.2.7 on 2025-10-09 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('spas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='spa',
            field=models.ForeignKey(blank=True, help_text='Spa where machine is installed (location inherited from spa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='spas.spa'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['serial_number'], name='idx_machine_serial'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['machine_code'], name='idx_machine_code'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status'], name='idx_machine_status'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['spa'], name='idx_machine_spa'),
        ),
    ]
