# Generated by Django 5.2.7 on 2025-10-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_alter_machine_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Unique serial number (optional)', max_length=100, null=True),
        ),
    ]
