# Generated by Django 5.2.7 on 2025-10-12 12:42

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('spas', '0002_fourthowner_thirdowner_spa_fourth_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=apps.documents.models.owner_document_upload_path)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_type', models.CharField(blank=True, help_text='Type of owner: primary, secondary, third, or fourth', max_length=20, null=True)),
                ('fourth_owner', models.ForeignKey(blank=True, help_text='Fourth owner this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='spas.fourthowner')),
                ('primary_owner', models.ForeignKey(blank=True, help_text='Primary owner this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='spas.primaryowner')),
                ('secondary_owner', models.ForeignKey(blank=True, help_text='Secondary owner this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='spas.secondaryowner')),
                ('third_owner', models.ForeignKey(blank=True, help_text='Third owner this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='spas.thirdowner')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['primary_owner'], name='idx_odoc_primary'), models.Index(fields=['secondary_owner'], name='idx_odoc_secondary'), models.Index(fields=['third_owner'], name='idx_odoc_third'), models.Index(fields=['fourth_owner'], name='idx_odoc_fourth'), models.Index(fields=['owner_type'], name='idx_odoc_type'), models.Index(fields=['title'], name='idx_odoc_title')],
            },
        ),
    ]
