# Generated by Django 5.2.7 on 2025-10-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('spas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='spa',
            field=models.ForeignKey(blank=True, help_text='Spa this document belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='spas.spa'),
        ),
    ]
