# Generated by Django 5.2.4 on 2025-10-07 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='idx_doc_spa_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='spa',
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'doc_type'], name='idx_doc_user_type'),
        ),
    ]
