# Generated by Django 5.2.4 on 2025-10-15 05:33

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_ownerdocument'),
        ('spas', '0003_spamanager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaManagerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=apps.documents.models.spa_manager_document_upload_path)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_name', models.CharField(blank=True, max_length=200, null=True)),
                ('spa_manager', models.ForeignKey(help_text='Spa manager this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='spas.spamanager')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_manager_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spa_manager_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['spa_manager'], name='idx_smdoc_spa_manager'), models.Index(fields=['title'], name='idx_smdoc_title')],
            },
        ),
    ]
