# Generated by Django 5.2.7 on 2025-10-09 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Primary user (legacy field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users who have access to this document (legacy, optional)', related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type'], name='idx_doc_type'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['spa'], name='idx_doc_spa'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['spa_code'], name='idx_doc_spa_code'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='idx_doc_title'),
        ),
    ]
