# Generated by Django 5.2.7 on 2025-10-15 10:46

import apps.documents.models
import apps.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_spamanagerdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[apps.documents.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='ownerdocument',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.owner_document_upload_path, validators=[apps.documents.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='spamanagerdocument',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.spa_manager_document_upload_path, validators=[apps.documents.validators.validate_document_file]),
        ),
    ]
